name: Bot Tu Dong Quet HTML  # Tên này sẽ hiện ở cột bên trái

on:
  push:
    branches:
      - main
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run script
        env:
          MY_EMAIL_PASS: ${{ secrets.MY_EMAIL_PASS }}
        # QUAN TRỌNG: Sửa 'chay_bot.py' thành đúng tên file chứa code Python của anh
        run: python chay_bot.py
